from django.urls import path
from .views import (
    ServiceRetrieveUpdateDeleteView,
    ServiceListView,
    ServiceCreateView,
    ServiceClientDetailView,
    RestaurantListView,
    AdminServiceListView,
    CustomerServiceAdminDeleteView,
    CustomerServiceAdminUpdateView,
    CustomerServiceAdminListView,
    CustomerServiceCreateView,
    CustomerServiceDetailView,
    CustomerServiceListView,
    CustomerServiceClientDetailView,
    QuestionListCreateView,
    QuestionRetriveUpdateDeleteView,
    QuestionWithAnswersListView,
    BulkFeedbackCreateView,
    QuestionListView,
    HotelRoomListCreateView,
    HotelRoomGetByNameView,
    HotelRoomRetrieveUpdateDeleteView,
    FeedbackListView,
    FeedbackAnswersListByQuestionView,
    FeedbackStatisticView
)

urlpatterns=[
    path('hotel/service/<str:slug>', ServiceRetrieveUpdateDeleteView.as_view(), name='service_get'),
    path('hotel/service/client/<str:lang>/<str:slug>', ServiceClientDetailView.as_view(), name='service_get_detail'),
    path('hotel/service/list/<str:lang>/<str:username>', ServiceListView.as_view(), name='service_list'),
    path('hotel/restaurant/list/<str:username>', RestaurantListView.as_view(), name='restaurant_list'),
    path('hotel/service/', ServiceCreateView.as_view(), name='service_create'),
    path('hotel/admin/services/', AdminServiceListView.as_view(), name='hotel_admin_services'),
    path('hotel/customer/services/<str:lang>/<str:username>', CustomerServiceListView.as_view() ,name='customer_service_list'),
    path('hotel/customer/service/<str:slug>', CustomerServiceDetailView.as_view() ,name='customer_service_detail'),
    path('hotel/customer/service/client/<str:lang>/<str:slug>', CustomerServiceClientDetailView.as_view() ,name='customer_service_client_detail'),
    path('hotel/customer/service/', CustomerServiceCreateView.as_view() ,name='customer_service_create'),
    path('hotel/customer/service/admin/list/', CustomerServiceAdminListView.as_view() ,name='customer_service_admin_list'),
    path('hotel/customer/service/admin/update/<str:slug>', CustomerServiceAdminUpdateView.as_view() ,name='customer_service_admin_update'),
    path('hotel/customer/service/admin/delete/<str:slug>', CustomerServiceAdminDeleteView.as_view() ,name='customer_service_admin_delete'),
    path('hotel-feedback/question', QuestionListCreateView.as_view(), name='question_list_create'),
    path('hotel-feedback/question-with-feedback', QuestionWithAnswersListView.as_view(), name='question_with_feedback_list'),
    path('hotel-feedback/question/list/<str:lang>/<str:username>', QuestionListView.as_view(), name='question_list'),
    path('hotel-feedback/question/<str:question_id>', QuestionRetriveUpdateDeleteView.as_view(), name='question_retrieve_update_delete'),
    path('hotel-feedback/create', BulkFeedbackCreateView.as_view(), name='bulk_feedback_create'),
    path('hotel-feedback/list', FeedbackListView.as_view(), name='feedback_list'),
    path('hotel-feedback/statistic', FeedbackStatisticView.as_view(), name='feedback_statistic'),
    path('hotel-feedback/list-by-question/<int:question_id>', FeedbackAnswersListByQuestionView.as_view(), name='feedback_list_by_question'),
    path('hotel-room/list-create', HotelRoomListCreateView.as_view(), name='hotel_room_list_create'),
    path('hotel-room/<int:id>', HotelRoomRetrieveUpdateDeleteView.as_view(), name='hotel_room_retrieve_update_delete'),
    path('hotel-room/id/<str:username>/<str:name>', HotelRoomGetByNameView.as_view(), name='hotel_room_id_get'),
]